version: 0.2
REPOSITORIESS: "result vote worker"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # - aws --version
      # - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 864899853618.dkr.ecr.ap-south-1.amazonaws.com$(aws ecr get-login --no-include-email --region ap-south-1)
      # - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 864899853618.dkr.ecr.ap-southeast-1.amazonaws.com
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 864899853618.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=864899853618.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - for repo in $REPOSITORIES; do
          echo "Building image for $repo";
          cd $repo;
          docker build -t $REPOSITORY_URI:$IMAGE_TAG:$repo .;
          docker tag $REPOSITORY_URI:$IMAGE_TAG:$repo:latest 864899853618.dkr.ecr.us-east-1.amazonaws.com/$repo:latest;
          cd ..;
        done
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - for repo in $REPOSITORIES; do
          echo "Building image for $repo";
          cd $repo;
          docker push $$REPOSITORY_URI:$IMAGE_TAG:$repo:latest;
          docker push $$REPOSITORY_URI:$IMAGE_TAG:$repo;
      - echo Writing image definitions file...;
      - printf '[{"name":"my-cicd-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json;
          cd ..;
        done
  artifacts:
  files:
    - imagedefinitions.json