version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 864899853618.dkr.ecr.ap-southeast-1.amazonaws.com
      - REPOSITORY_URI_vote=864899853618.dkr.ecr.ap-southeast-1.amazonaws.com/vote
      - REPOSITORY_URI_result=864899853618.dkr.ecr.ap-southeast-1.amazonaws.com/result
      - REPOSITORY_URI_worker=864899853618.dkr.ecr.ap-southeast-1.amazonaws.com/worker

  build:
    commands:
    # Building vote image 
      - echo Build started for Votting image on `date`
      - docker build -t vote ./vote
      - docker tag vote:latest $REPOSITORY_URI_vote:latest
    
    # Building result image 
      - echo Build started for Result image on `date`
      - docker build -t result ./result
      - docker tag result:latest $REPOSITORY_URI_result:latest

    # Building worker image 
      - echo Build started for Worker image on `date`
      - docker build -t worker ./worker
      - docker tag worker:latest $REPOSITORY_URI_worker:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing all Docker images to ECR...
      - docker push $REPOSITORY_URI_vote:latest
      - docker push $REPOSITORY_URI_result:latest
      - docker push $REPOSITORY_URI_worker:latest
artifacts:
  files:
    - imagedefinitions.json